### ISSUE TITLE
后期是否考虑支持站内音乐

### ISSUE THREAD

**Issue by zhuangzhuangY** [0xforee/nas-tools-bk#10]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:  v3.3.15
> 环境: docker 

## 你想要新增或者改进什么功能？
> 目前站内均有日常歌曲音乐分类，可否考虑在现有环境上支持搜索歌曲的下载，增加下载器中的音乐目录。

## 这个功能有什么可以参考的资料吗？

> 无

**Comment by 0xforee** [comment]
暂时不支持，观影还有很多需要优化的
