### ISSUE TITLE
【优化建议】建议Cookiecloud直接改成插件版，插件版还可以定时更新

### ISSUE THREAD

**Issue by jackloves111** [0xforee/nas-tools-bk#3]
最新版[v3.1.5-alpha.1 d4caa67](https://github.com/0xforee/nas-tools)

![image](https://github.com/0xforee/nas-tools/assets/89971817/91ee1e81-3185-4c83-8949-b56cee9c8b7c)

## 当前版本cookiecloud只能更新cookie，不能添加站点

![image](https://github.com/0xforee/nas-tools/assets/89971817/b5dae404-4d0a-4071-8d0d-00b36f231d9a)

建议直接改成H佬的插件版，插件版还可以定时更新

这里

https://github.com/hsuyelin/nas-tools/blob/master/app/plugins/modules/cookiecloud.py

![image](https://github.com/0xforee/nas-tools/assets/89971817/9f0897b5-00ae-4941-bfc6-b0b2c3c7dffd)

**Comment by jackloves111** [comment]
另外，如何阻止cookiecloud更新替换馒头API问题？

**Comment by 0xforee** [comment]
已添加（带黑白名单），可以拉取最新代码试试
