### ISSUE TITLE
【优化建议】站点文件使用hsuyelin版本，他这个用json生成，方便维护，方便其他用户提交PR更新

### ISSUE THREAD

**Issue by jackloves111** [0xforee/nas-tools-bk#4]
![image](https://github.com/0xforee/nas-tools/assets/89971817/66708d38-f98d-47dd-b9bc-51996ff1c660)

站点文件是否可以使用hsuyelin版本的，因为他专门做了一个站点维护的程序，方便其他用户提交PR

这里

https://github.com/hsuyelin/nas-tools-sites

![image](https://github.com/0xforee/nas-tools/assets/89971817/1076833a-ea23-46b4-a422-5dfed6bc7e18)

我是把他的一些我觉得优点的地方提出来了，你可以看自己喜欢决定是否参考

**Comment by 0xforee** [comment]
拉取下最新代码就行

**Comment by jackloves111** [comment]
> 拉取下最新代码就行

可能是我描述的不对，我原意是他那个程序，可以把json生成dat文件，没想到大佬直接更新了dat文件，也可以吧，就是大佬能否开源dat的生成程序，方便我等也可以维护更新，现在的dat我没有办法解包修改和打包
