### ISSUE TITLE
刷流用不了，

### ISSUE THREAD

**Issue by huang3370** [0xforee/nas-tools-bk#8]
刷流一直提示错误，部分下载错误，存在，
![IMG_0605](https://github.com/0xforee/nas-tools/assets/165783634/3d35d397-f834-4d6f-9c57-8262aabbe0ee)

**Comment by huang3370** [comment]
这到底什么原因

**Comment by 0xforee** [comment]
是磁盘空间不够，或者磁盘映射有问题
