### ISSUE TITLE
20240404，docker拉latest镜像无法运行

### ISSUE THREAD

**Issue by LSP0123** [0xforee/nas-tools-bk#9]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本:latest
>
> 环境: docker   aarch64

## 你遇到什么问题了？
无法运行

```
nas-tools  | 更新程序...
nas-tools  | From https://github.com/0xforee/nas-tools
nas-tools  |  * branch            master     -> FETCH_HEAD
nas-tools  | HEAD is now at 7c257a4 Merge pull request #7 from jackloves111/master
nas-tools  | 更新成功...
nas-tools  | 以PUID=1000，PGID=1000的身份启动程序...
nas-tools  | 启动Redis...
nas-tools  | 28:C 04 Apr 2024 13:14:44.950 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
nas-tools  | 2024-04-04T13:14:46: PM2 log: Launching in no daemon mode
nas-tools  | 2024-04-04T13:14:46: PM2 log: App [NAStool:0] starting in -fork mode-
nas-tools  | 2024-04-04T13:14:46: PM2 log: App [NAStool:0] online
nas-tools  | 正在加载配置：/config/config.yaml
nas-tools  | Traceback (most recent call last):
nas-tools  |   File "/nas-tools/run.py", line 32, in 
nas-tools  |     from web.action import WebAction
nas-tools  |   File "/nas-tools/web/action.py", line 44, in 
nas-tools  |     from web.backend.user import User
nas-tools  | ModuleNotFoundError: No module named 'web.backend.user'
nas-tools  | 2024-04-04T13:15:00: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
nas-tools  | 2024-04-04T13:15:00: PM2 log: App [NAStool:0] starting in -fork mode-
nas-tools  | 2024-04-04T13:15:00: PM2 log: App [NAStool:0] online
nas-tools  | 正在加载配置：/config/config.yaml
```

似乎是alpine自带的python过低，需要升级到3.17
https://github.com/royzheng/nas-tools/issues/1

**Comment by 0xforee** [comment]
v3.4.1 版本发布
https://github.com/0xforee/nas-tools/releases/tag/v3.4.1
更新内容：
这个版本是基于 hsuyelin版 更新而来，原版的功能基本已迁移完成。有问题可以提 issue
同时也是基于官方 3.2.3 版本的改动，也包含了官方的历史升级内容
除以上内容，迁移了原有的独特改动，详情见 https://github.com/0xforee/nas-tools/blob/master/diff.md
升级注意：
此版本降级到python3.10 版本（有一个依赖库不支持3.11），如果之前使用过 0xforee 的系列，更新此版本需要重新拉取新镜像（无法直接更新镜像，可能会启动报错），并新开docker。可以通过直接可以重新复制配置文件新开。

**Comment by 0xforee** [comment]
> ## 你使用的 NAStool 是什么版本，什么环境？
> > NAStool 版本:latest
> > 环境: docker   aarch64
> 
> ## 你遇到什么问题了？
> 无法运行
> 
> ```
> nas-tools  | 更新程序...
> nas-tools  | From https://github.com/0xforee/nas-tools
> nas-tools  |  * branch            master     -> FETCH_HEAD
> nas-tools  | HEAD is now at 7c257a4 Merge pull request #7 from jackloves111/master
> nas-tools  | 更新成功...
> nas-tools  | 以PUID=1000，PGID=1000的身份启动程序...
> nas-tools  | 启动Redis...
> nas-tools  | 28:C 04 Apr 2024 13:14:44.950 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
> nas-tools  | 2024-04-04T13:14:46: PM2 log: Launching in no daemon mode
> nas-tools  | 2024-04-04T13:14:46: PM2 log: App [NAStool:0] starting in -fork mode-
> nas-tools  | 2024-04-04T13:14:46: PM2 log: App [NAStool:0] online
> nas-tools  | 正在加载配置：/config/config.yaml
> nas-tools  | Traceback (most recent call last):
> nas-tools  |   File "/nas-tools/run.py", line 32, in 
> nas-tools  |     from web.action import WebAction
> nas-tools  |   File "/nas-tools/web/action.py", line 44, in 
> nas-tools  |     from web.backend.user import User
> nas-tools  | ModuleNotFoundError: No module named 'web.backend.user'
> nas-tools  | 2024-04-04T13:15:00: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
> nas-tools  | 2024-04-04T13:15:00: PM2 log: App [NAStool:0] starting in -fork mode-
> nas-tools  | 2024-04-04T13:15:00: PM2 log: App [NAStool:0] online
> nas-tools  | 正在加载配置：/config/config.yaml
> ```
> 
> 似乎是alpine自带的python过低，需要升级到3.17 [royzheng/nas-tools#1](https://github.com/royzheng/nas-tools/issues/1)

用我发的新版本试试

**Comment by LSP0123** [comment]
- NASTOOL_AUTO_UPDATE=true
      - NASTOOL_CN_UPDATE=true
成功安装
